# Generated by Django 3.2.6 on 2021-08-12 16:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '13. Availability',
            },
        ),
        migrations.CreateModel(
            name='BatteryCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '05. Battery Capacity',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='Brand_img/')),
            ],
            options={
                'verbose_name_plural': '02. Brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '01. Categories',
            },
        ),
        migrations.CreateModel(
            name='FrontCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '08. Front Camera',
            },
        ),
        migrations.CreateModel(
            name='InternalStorage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '04. Internal Storage',
            },
        ),
        migrations.CreateModel(
            name='NetworkConnectivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '10. Network Connectivity',
            },
        ),
        migrations.CreateModel(
            name='NumberOfCores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name_plural': '12. Number Of Cores',
            },
        ),
        migrations.CreateModel(
            name='OperatingSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '09. Operating System',
            },
        ),
        migrations.CreateModel(
            name='PrimaryRearCamera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '07. Primary Rear Camera',
            },
        ),
        migrations.CreateModel(
            name='ProcessorSpeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '11. Processor Speed',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Model', models.CharField(max_length=200)),
                ('image', models.ImageField(upload_to='Product_img/')),
                ('Availability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.availability')),
                ('BatteryCapacity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.batterycapacity')),
                ('FrontCamera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.frontcamera')),
                ('InternalStorage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.internalstorage')),
                ('NetworkConnectivity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.networkconnectivity')),
                ('NumberOfCores', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.numberofcores')),
                ('OperatingSystem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.operatingsystem')),
                ('PrimaryRearCamera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.primaryrearcamera')),
                ('ProcessorSpeed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.processorspeed')),
            ],
            options={
                'verbose_name_plural': '13. Product',
            },
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '03. RAM',
            },
        ),
        migrations.CreateModel(
            name='ScreenSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name_plural': '06. Screen Size',
            },
        ),
        migrations.CreateModel(
            name='Specifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Brand', models.CharField(max_length=50)),
                ('Model_Name', models.CharField(max_length=50)),
                ('Price_in_india', models.IntegerField()),
                ('Release_Data', models.CharField(max_length=50)),
                ('Dimensions', models.CharField(max_length=50)),
                ('Weight', models.CharField(max_length=50)),
                ('Battery_capacity', models.IntegerField()),
                ('Fast_charging', models.CharField(max_length=50)),
                ('Colours', models.CharField(max_length=50)),
                ('Screen_Size', models.IntegerField()),
                ('Touchscreen', models.CharField(max_length=5)),
                ('Resolution', models.CharField(max_length=20)),
                ('Protection_type', models.CharField(max_length=20)),
                ('Aspect_ratio', models.CharField(max_length=20)),
                ('Processor_make', models.CharField(max_length=50)),
                ('RAM', models.CharField(max_length=5)),
                ('Internal_storage', models.CharField(max_length=10)),
                ('Rear_Camera', models.CharField(max_length=200)),
                ('No_of_Rear_Cameras', models.IntegerField()),
                ('Rear_autofocus', models.CharField(max_length=5)),
                ('Rear_flash', models.CharField(max_length=5)),
                ('Front_Camera', models.CharField(max_length=200)),
                ('No_of_Front_Cameras', models.IntegerField()),
                ('Operating_system', models.CharField(max_length=50)),
                ('Skin', models.CharField(max_length=50)),
                ('Wi_fi', models.CharField(max_length=5)),
                ('GPS', models.CharField(max_length=5)),
                ('Bluetooth', models.CharField(max_length=20)),
                ('USB_Type_C', models.CharField(max_length=5)),
                ('Number_of_SIMs', models.IntegerField()),
                ('In_Display_Fingerprint_Sensor', models.CharField(max_length=5)),
                ('Compass_Magnetometer', models.CharField(max_length=5)),
                ('Proximity_sensor', models.CharField(max_length=5)),
                ('Accelerometer', models.CharField(max_length=5)),
                ('Ambient_light_sensor', models.CharField(max_length=5)),
                ('Gyroscope', models.CharField(max_length=5)),
                ('Model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'verbose_name_plural': '13. Specifications',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='RAM',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.ram'),
        ),
        migrations.AddField(
            model_name='product',
            name='ScreenSize',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.screensize'),
        ),
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.brand'),
        ),
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.category'),
        ),
    ]
