# Generated by Django 3.2.6 on 2021-08-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210812_2302'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Thumbnail',
            field=models.ImageField(blank=True, upload_to='Brand_img/'),
        ),
    ]
