# Generated by Django 3.2.6 on 2021-08-15 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_product_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Thumbnail',
            field=models.ImageField(blank=True, upload_to='Mobile_img/'),
        ),
        migrations.AlterField(
            model_name='specifications',
            name='Model',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.product'),
        ),
    ]
