# Generated by Django 3.2.6 on 2021-08-16 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20210815_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='specifications',
            name='FiveG',
            field=models.CharField(default='Yes', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specifications',
            name='FourG',
            field=models.CharField(default='Yes', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specifications',
            name='GSM_CDMA',
            field=models.CharField(default='GSM', max_length=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specifications',
            name='Processor_Core',
            field=models.CharField(default='octa core', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specifications',
            name='Sim_Type',
            field=models.CharField(default='Nano-Type', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='specifications',
            name='ThreeG',
            field=models.CharField(default='Yes', max_length=5),
            preserve_default=False,
        ),
    ]
